#!/usr/bin/env python3

from sys import argv
import pypdf

# parse the args

args = argv[1:]

path_chapters = None

assert '-c' in args

index_opt_c = args.index('-c')
path_chapters = args[index_opt_c + 1]
del args[index_opt_c]
del args[index_opt_c]

opt_import_outline = '-i' in args
if opt_import_outline:
    del args[args.index('-i')]

assert len(args) >= 3

path_output = args[-1]
paths_input = args[:-1]

# open readers for all input files
readers = [pypdf.PdfReader(path) for path in paths_input]

with open(path_chapters) as fin:
    chapters = [line.strip() for line in fin.readlines()]

assert len(readers) == len(chapters)

writer = pypdf.PdfWriter()
for i, (reader, chapter) in enumerate(zip(readers, chapters)):
    writer.append(reader, outline_item=chapter, pages=(0, len(reader.pages)),
                  import_outline=opt_import_outline)

with open(path_output, 'wb') as fout:
    writer.write(fout)
